# Generated by Django 4.2 on 2024-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Укажите Имя', max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Укажите Фамилию', max_length=200, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваш email')),
                ('time_reserved', models.TimeField(blank=True, help_text='Укажите время', null=True, verbose_name='Время бронирования')),
                ('date_reserved', models.DateField(blank=True, help_text='Укажите дату', null=True, verbose_name='Дата бронирования')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Признак брони')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table', models.IntegerField(help_text='Укажите номер стола', primary_key=True, serialize=False, verbose_name='Номер стола')),
                ('seats', models.IntegerField(help_text='Количество мест', verbose_name='Количество мест')),
                ('min_people', models.IntegerField(blank=True, help_text='Введите минимальное количество людей', null=True, verbose_name='Минимум человек')),
                ('max_people', models.IntegerField(blank=True, help_text='Введите максимальное количество людей', null=True, verbose_name='Максимум человек')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reservation/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
    ]
